// Credit to the Arbitration Goons for this data and their continued study of this field.

window.arbyTiers = {
	SolNode450: "S",
	SolNode106: "S",
	SolNode25: "S",
	SolNode719: "S",
	SolNode64: "S",
	SolNode147: "A",
	SolNode23: "A",
	SolNode172: "A",
	SolNode167: "B",
	ClanNode24: "B",
	SolNode149: "B",
	ClanNode22: "B",
	ClanNode18: "B",
	SolNode164: "B",
	SolNode707: "B",
	SolNode211: "B",
	SolNode42: "B",
	SolNode195: "B",
	SolNode408: "B",
	SolNode402: "B",
	SolNode412: "C",
	ClanNode2: "C",
	SolNode46: "C",
	ClanNode8: "C",
	SolNode212: "C",
	SolNode22: "C",
	SolNode224: "C",
	SolNode26: "C",
	ClanNode6: "C",
	SolNode122: "C",
	SolNode72: "C",
	SolNode130: "D",
	ClanNode15: "D",
	SolNode85: "D",
	SolNode18: "D",
	SolNode305: "D",
	ClanNode4: "D",
	SolNode125: "D",
};

/* Recommended number of Cyte-09s:

{
	"Tyana Pass": 2,
	"Alator": 2,
	"Callisto": 2,
	"Munio": 2,
	"Umbriel": 2,
	"Cinxia": 2,
	"Cytherean": 2,
	"Xini": 2,
	"Oestrus": 2,
	"Sechura": 2,
	"Casta": 0,
	"Seimeni": 0,
	"Akkad": 2,
	"Kala-azar": 2,
	"Hyf": 1,
	"Ose": 1,
	"Helene": 1,
	"Hydron": 1,
	"Belenus": 2,
	"Taranis": 2,
	"Mithra": 2,
	"Coba": 2,
	"Spear": 1,
	"Kadesh": 1,
	"Paimon": 0,
	"Tessera": 1,
	"Odin": 2,
	"Lith": 2,
	"Larzac": 0,
	"Stephano": 1,
	"Outer Terminus": 1,
	"Lares": 1,
	"Sangeru": 1,
	"Gaia": 2,
	"Rhea": 1,
	"Stöfler": 2,
	"Sinai": 2,
	"Io": 2
}

*/
