import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import process from 'node:process';
import {
	describe, test, expect, beforeEach,
} from 'vitest';
import {JSDOM} from 'jsdom';

describe('Arbitration Schedule (/arbys)', () => {
	let dom: JSDOM;
	let document: Document;

	beforeEach(() => {
		// Load the rendered arbys.html from public/ (generated by scripts/render-pages.js)
		let html = readFileSync(join(process.cwd(), 'public/arbys.html'), 'utf8');
		html = html.replaceAll(/<style>[\s\S]*?<\/style>/gu, '<style></style>');

		dom = new JSDOM(html, {
			url: 'https://browse.wf/arbys',
		});
		document = dom.window.document;
	});

	describe('HTML structure: Dropdown selectors', () => {
		test('days selector has all expected options', () => {
			const select = document.querySelector<HTMLSelectElement>('#select-days');
			expect(select).toBeTruthy();

			const values = [...select!.options].map(opt => opt.value);
			expect(values).toContain('1'); // 24 hours
			expect(values).toContain('7'); // 7 days
			expect(values).toContain('14'); // 14 days (default)
			expect(values).toContain('30'); // 30 days
			expect(values).toContain('90'); // 90 days
			expect(values).toContain('365'); // 12 months
			expect(values).toContain('9999999999'); // Eon
		});

		test('days selector defaults to 14 days', () => {
			const select = document.querySelector<HTMLSelectElement>('#select-days');
			const defaultOption = [...select!.options].find(opt => opt.selected);
			expect(defaultOption?.value).toBe('14');
		});

		test('timezone selector has local and UTC options', () => {
			const select = document.querySelector<HTMLSelectElement>('#select-tz');
			expect(select).toBeTruthy();

			const values = [...select!.options].map(opt => opt.value);
			expect(values).toContain('local');
			expect(values).toContain('zulu');
		});

		test('hour format selector has all three formats', () => {
			const select = document.querySelector<HTMLSelectElement>('#select-hourfmt');
			expect(select).toBeTruthy();

			const values = [...select!.options].map(opt => opt.value);
			expect(values).toContain('mil'); // Military time
			expect(values).toContain('24'); // 24-hour time
			expect(values).toContain('12'); // 12-hour time
		});
	});

	describe('HTML structure: Checkbox filters', () => {
		test('all mission type checkboxes exist', () => {
			const missionTypes = [
				'MT_SURVIVAL',
				'MT_DEFENSE',
				'MT_TERRITORY',
				'MT_EXCAVATE',
				'MT_PURIFY',
				'MT_EVACUATION',
				'MT_ARTIFACT',
				'MT_CORRUPTION',
				'MT_VOID_CASCADE',
				'MT_ARMAGEDDON',
				'MT_ALCHEMY',
			];

			for (const type of missionTypes) {
				const checkbox = document.querySelector<HTMLInputElement>(`#filter-${type}`);
				expect(checkbox, `filter-${type} should exist`).toBeTruthy();
				expect(checkbox!.type).toBe('checkbox');
				expect(checkbox!.checked).toBe(true); // All checked by default
			}
		});

		test('all tier checkboxes exist', () => {
			const tiers = ['S', 'A', 'B', 'C', 'D', 'F'];

			for (const tier of tiers) {
				const checkbox = document.querySelector<HTMLInputElement>(`#filter-tier-${tier}`);
				expect(checkbox, `filter-tier-${tier} should exist`).toBeTruthy();
				expect(checkbox!.type).toBe('checkbox');
				expect(checkbox!.checked).toBe(true);
			}
		});

		test('all faction checkboxes exist', () => {
			const factions = ['FC_GRINEER', 'FC_CORPUS', 'FC_INFESTATION', 'FC_OROKIN', 'FC_MITW'];

			for (const faction of factions) {
				const checkbox = document.querySelector<HTMLInputElement>(`#filter-${faction}`);
				expect(checkbox, `filter-${faction} should exist`).toBeTruthy();
				expect(checkbox!.type).toBe('checkbox');
				expect(checkbox!.checked).toBe(true);
			}
		});

		test('checkboxes have associated labels', () => {
			const allFilters = [
				'MT_SURVIVAL',
				'MT_DEFENSE',
				'MT_TERRITORY',
				'MT_EXCAVATE',
				'tier-S',
				'tier-A',
				'FC_GRINEER',
				'FC_CORPUS',
			];

			for (const filter of allFilters) {
				const checkbox = document.querySelector(`#filter-${filter}`);
				const label = document.querySelector(`label[for="filter-${filter}"]`);
				expect(label, `label for filter-${filter} should exist`).toBeTruthy();
				expect(label?.textContent).toBeTruthy();
			}
		});
	});

	describe('HTML structure: Next occurrence table', () => {
		test('table exists with correct structure', () => {
			const table = document.querySelector('table');
			expect(table).toBeTruthy();

			const thead = table?.querySelector('thead');
			expect(thead).toBeTruthy();
			expect(thead?.textContent).toContain('Next Occurrence');

			const tbody = table?.querySelector('tbody');
			expect(tbody).toBeTruthy();
		});

		test('has rows for all mission types', () => {
			const missionTypes = [
				'MT_SURVIVAL',
				'MT_DEFENSE',
				'MT_TERRITORY',
				'MT_EXCAVATE',
				'MT_PURIFY',
				'MT_EVACUATION',
				'MT_ARTIFACT',
				'MT_CORRUPTION',
				'MT_VOID_CASCADE',
				'MT_ARMAGEDDON',
				'MT_ALCHEMY',
			];

			for (const type of missionTypes) {
				const row = document.querySelector(`#next-${type}`);
				expect(row, `next-${type} row should exist`).toBeTruthy();

				// Row should have 3 columns: checkbox+label, date, details
				expect(row?.children.length).toBe(3);
			}
		});

		test('has rows for all tiers', () => {
			const tiers = ['S', 'A', 'B', 'C', 'D', 'F'];

			for (const tier of tiers) {
				const row = document.querySelector(`#next-tier-${tier}`);
				expect(row, `next-tier-${tier} row should exist`).toBeTruthy();
				expect(row?.children.length).toBe(3);
			}
		});

		test('has rows for all factions', () => {
			const factions = ['FC_GRINEER', 'FC_CORPUS', 'FC_INFESTATION', 'FC_OROKIN', 'FC_MITW'];

			for (const faction of factions) {
				const row = document.querySelector(`#next-${faction}`);
				expect(row, `next-${faction} row should exist`).toBeTruthy();
				expect(row?.children.length).toBe(3);
			}
		});
	});

	describe('HTML structure: Log container', () => {
		test('log element exists', () => {
			const log = document.querySelector('#log');
			expect(log).toBeTruthy();
			expect(log?.textContent).toContain('Loading, please wait...');
		});

		test('layout has two-column structure', () => {
			const row = document.querySelector('.row');
			expect(row).toBeTruthy();

			const columns = row?.querySelectorAll('[class*="col-"]');
			expect(columns?.length).toBeGreaterThanOrEqual(2);
		});
	});

	describe('URL fragment parameter support', () => {
		test('supports days parameter in URL structure', () => {
			// The arbys.ts code reads from URLSearchParams(location.hash.replace("#", ""))
			// This test verifies the selects have the right structure to be set programmatically
			const select = document.querySelector<HTMLSelectElement>('#select-days');

			// Should be able to set these values programmatically
			select!.value = '7';
			expect(select!.value).toBe('7');

			select!.value = '90';
			expect(select!.value).toBe('90');
		});

		test('supports tz parameter in URL structure', () => {
			const select = document.querySelector<HTMLSelectElement>('#select-tz');

			select!.value = 'zulu';
			expect(select!.value).toBe('zulu');

			select!.value = 'local';
			expect(select!.value).toBe('local');
		});

		test('supports hourfmt parameter in URL structure', () => {
			const select = document.querySelector<HTMLSelectElement>('#select-hourfmt');

			select!.value = '12';
			expect(select!.value).toBe('12');

			select!.value = '24';
			expect(select!.value).toBe('24');
		});

		test('checkboxes can be unchecked programmatically for exclude parameter', () => {
			const checkbox = document.querySelector<HTMLInputElement>('#filter-MT_SURVIVAL');

			expect(checkbox!.checked).toBe(true);
			checkbox!.checked = false;
			expect(checkbox!.checked).toBe(false);
		});
	});

	describe('HTML structure: Tileset filters', () => {
		const tilesets = [
			'CorpusGasCityTileset',
			'CorpusIcePlanetTileset',
			'CorpusIcePlanetTilesetCaves',
			'CorpusOutpostTileset',
			'CorpusShipTileset',
			'EntratiTileset',
			'GrineerAsteroidTileset',
			'GrineerForestTileset',
			'GrineerGalleonTileset',
			'GrineerOceanTileset',
			'GrineerSettlementTileset',
			'GrineerShipyardsTileset',
			'InfestedCorpusShipTileset',
			'OrokinDerelictTileset',
			'OrokinMoonTilesetCorpus',
			'OrokinMoonTilesetGrineer',
			'OrokinVoidTileset',
			'ZarimanTileset',
		];

		test('all tileset checkboxes exist', () => {
			for (const tileset of tilesets) {
				const checkbox = document.querySelector<HTMLInputElement>(`#filter-${tileset}`);
				expect(checkbox, `filter-${tileset} should exist`).toBeTruthy();
				expect(checkbox!.type).toBe('checkbox');
				expect(checkbox!.checked).toBe(true); // All checked by default
			}
		});

		test('has rows for all tilesets in Next Occurrence table', () => {
			for (const tileset of tilesets) {
				const row = document.querySelector(`#next-${tileset}`);
				expect(row, `next-${tileset} row should exist`).toBeTruthy();
				expect(row?.children.length).toBe(3);
			}
		});
	});

	describe('HTML structure: Table category headings', () => {
		test('has all category headings', () => {
			const headings = [...document.querySelectorAll('tbody tr.category-heading')];
			expect(headings.length).toBe(4);

			expect(headings[0]?.textContent).toContain('Mission Types');
			expect(headings[1]?.textContent).toContain('Tiers');
			expect(headings[2]?.textContent).toContain('Factions');
			expect(headings[3]?.textContent).toContain('Tilesets');
		});
	});

	describe('HTML structure: Save/Load buttons', () => {
		test('Save settings button exists', () => {
			const btn = document.querySelector<HTMLButtonElement>('#btn-save-settings');
			expect(btn, 'Save settings button should exist').toBeTruthy();
			expect(btn!.tagName).toBe('BUTTON');
			expect(btn!.textContent).toContain('Save settings');
		});

		test('Load settings button exists and starts disabled', () => {
			const btn = document.querySelector<HTMLButtonElement>('#btn-load-settings');
			expect(btn, 'Load settings button should exist').toBeTruthy();
			expect(btn!.tagName).toBe('BUTTON');
			expect(btn!.textContent).toContain('Restore settings');
			expect(btn!.disabled, 'Load button should start disabled').toBe(true);
		});
	});
});
